# kategori

GET http://localhost:3000/kategori

###
GET http://localhost:3000/kategori/637222de356396bb553b67ef


###
POST http://localhost:3000/kategori
Content-Type: application/json

{
    "id" : 5,
    "nama_kategori" : "Triller"
}

###
PATCH http://localhost:3000/kategori/637222de356396bb553b67ef
Content-Type: application/json

{
    "id" : 2,
    "nama_kategori" : "jamal"
}

###
DELETE  http://localhost:3000/kategori/637227d21bfa13bace2d0188